### ISSUE TITLE
MultipleUniqueKeyFoundException for string primary key

### ISSUE THREAD

**Issue by kachalkov** [zzzprojects/nmemory#1]
Hi,
Awesome effort and library!

We are experiencing issue with database tables which has string primary keys with data which is different only by case sensitive which is not working for in memory scenario:

```
    public void Insert(TKey key, TEntity entity)
    {
        if (this.inner.ContainsKey(key))
        {
            throw new MultipleUniqueKeyFoundException();
        }
        else
        {
            this.inner.Add(key, entity);
        }

        this.Count++;
    }
```

Any ideas on how this could be fixed?

**Comment by tamasflamich** [comment]
Hi,

Yes, capability for being case insensitive has been requested long ago. Unfortunately this would require deep architectural changes that I probably will not have resources for.

**Comment by tamasflamich** [comment]
This issue describes the problem better : https://github.com/tamasflamich/nmemory/issues/6
