### ISSUE TITLE
Enhancement : interpreting Sql Queries

### ISSUE THREAD

**Issue by CedricDumont** [zzzprojects/nmemory#10]
Hi,

Would it be difficult to make NMemory interpret Sql Queries ? 
like having a kind of driver that would transform Sql queries to what NMemory understands as queries. it would be then possible to provide a layer between Sqlserver data client or oracle data client to deal with NMemory ? 
if interrested, I would love to help on this. Like you I don't have that much time, but it could be fun and interresting to implement as I cannot see places to find pure in memory DB for .net.

This would be very usefull for testing

**Comment by tamasflamich** [comment]
Hi @CedricDumont - Language parsing is a very large area of computer science. Unfortunately I don't really have experience with it, but I would guess it would require a large amount of effort to create a sql -> linq expression tree converter.
