### ISSUE TITLE
Question: is it optimized for within range search?

### ISSUE THREAD

**Issue by AqlaSolutions** [zzzprojects/nmemory#11]
Can I make queries like `Where(x=>x.a>=9 && x.a<=10 && x.b>=5 && x.b<=6 && x.c>=3 && x.c<=12)`? Will it use ordered indexes? Binary search?

**Comment by tamasflamich** [comment]
Hi @AqlaSolutions - The primary goal of this library is to serve as the underlying engine of the Effort testing library. These kind of optimizations are not included in the query optimizer.
