### ISSUE TITLE
Is "Delete Database" implemented?

### ISSUE THREAD

**Issue by johnknoop** [zzzprojects/nmemory#15]
Calling `dbContext.Delete()` followed by `dbContext.Create()` throws an exception saying it can't create a database that already exists.

John

**Comment by JonathanMagnan** [comment]
Hello @johnknoop ,

We are currently cleaning all issue of `NMemory` before doing the same for `Effort`.

Since that issue is related to `Effort`, I have "moved' it here: https://github.com/zzzprojects/EntityFramework-Effort/issues/126

Best Regards,

Jonathan
