### ISSUE TITLE
"order by" not working

### ISSUE THREAD

**Issue by maximpashuk** [zzzprojects/nmemory#16]
Example

```csharp
    class Order
    {
        public long Id { get; set; }
        public string Name { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var db = new Database();

            var orderTable = db.Tables.Create<Order, long>(x => x.Id, null);
            orderTable.Insert(new Order { Id = 1, Name = "Order1" });

            var query = from order in orderTable
                        orderby order.Id
                        select order;

            var test = query.ToList();
        }
    }
```

Exception thrown **"Unable to cast object of type 'NMemory.Linq.TableQuery\`1[Order]' to type 'System.Linq.IOrderedQueryable\`1[Order]'"**

![bug](https://cloud.githubusercontent.com/assets/5028850/21091308/f2cbc678-c077-11e6-9fa0-0e3533c21220.png)

Since LINQ interface ```System.Linq.IOrderedQueryable<T>``` is only a marker interface, I think ```NMemory.Tables.DefaultTable<TEntity,TPrimaryKey>``` should implement it.

After that this problem should gone.

**Comment by JonathanMagnan** [comment]
Hello @maximpashuk ,

This issue has been fixed in the latest version v2.0.2

Best Regards,

Jonathan
