### ISSUE TITLE
Update your sample code!

### ISSUE THREAD

**Issue by aaronscribner** [zzzprojects/nmemory#18]
To match the current library!!!!!!!!!

**Comment by gravbox** [comment]
That would be great. I am trying to get this to work and the sample is not working. I am plowing through it without any examples.

**Comment by aaronscribner** [comment]
I think this repo is dead.

**Comment by JonathanMagnan** [comment]
Hello @aaronscribner ,

My company took the ownership of this project at the end of `2017`, so no the repository is not dead (it took us, however, a few months before starting to support it)

A website has been created: http://nmemory.net/ and soon example/documentation will be updated to make it available on .NET Fiddle (https://dotnetfiddle.net/).

Even if this request is not yet completed, I will close it to make it easier for us to follow other request. We are currently heavily working on all our librairies documentations so this project will be eventually be done.

Best Regards,

Jonathan
