### ISSUE TITLE
Interested in a cross-platform version?

### ISSUE THREAD

**Issue by xivk** [zzzprojects/nmemory#20]
Would you be interested in a pull-request enabling cross-platform support? I'm thinking netstandard...?

I would like to use nmemory for the next version of the GTFS-library. It keeps large lists of objects in-memory but it's difficult to query. nmemory could be a solution:

https://github.com/itinero/GTFS/

**Comment by JonathanMagnan** [comment]
Hello @xivk ,

Just to let you known that NMemory now support .NET Standard 2.0 since 1 month ago

NuGet: https://www.nuget.org/packages/NMemory/

Best Regards,

Jonathan
