### ISSUE TITLE
TableCollection.RegisterTable does not check unicity

### ISSUE THREAD

**Issue by damien-r** [zzzprojects/nmemory#21]
In the method NMemory.Tables.TableCollection.RegisterTable(ITable table), there is no check if table already contains the EntityType. This can lead to an error in the FindTable method when calling SingleOrDefault.

For more details, see https://github.com/tamasflamich/effort/issues/33

**Comment by JonathanMagnan** [comment]
Hello @damien-r ,

Thank for reporting and your fix.

The fix has been added in the latest version 2.0.2

Best Regards,

Jonathan
