### ISSUE TITLE
Not Compatible with DBFunction.Like starts with

### ISSUE THREAD

**Issue by lmk1988** [zzzprojects/nmemory#30]
Using DBFunction.Like 'aaa%' will return results even if matching string did not start with 'aaa'

This is because the regex used in 
https://github.com/zzzprojects/nmemory/blob/eac09f8ad6489bd693334b8c32afe51848e71f66/Main/Source/NMemory.Shared/Functions.cs
does not have a ^ in front

Is it possible to update the LIKE function in this URL to match the updated one in
https://stackoverflow.com/questions/5663655/like-operator-in-linq-to-objects

**Comment by JonathanMagnan** [comment]
Hello @lmk1988 ,

Just to make sure, you want us to update for this one:

```csharp
public static class LikeExtension
{
    public static IEnumerable<T> Like<T>(this IEnumerable<T> source, Func<T, string> selector, string pattern)
    {
        var regex = new Regex(ConvertLikeToRegex(pattern), RegexOptions.IgnoreCase);
        return source.Where(t => IsRegexMatch(selector(t), regex));
    }

    static bool IsRegexMatch(string input, Regex regex)
    {
        if (input == null)
            return false;

        return regex.IsMatch(input);
    }

    static string ConvertLikeToRegex(string pattern)
    {
        StringBuilder builder = new StringBuilder();
        // Turn "off" all regular expression related syntax in the pattern string
        // and add regex begining of and end of line tokens so '%abc' and 'abc%' work as expected
        builder.Append("^").Append(Regex.Escape(pattern)).Append("$");

        /* Replace the SQL LIKE wildcard metacharacters with the
        * equivalent regular expression metacharacters. */
        builder.Replace("%", ".*").Replace("_", ".");

        /* The previous call to Regex.Escape actually turned off
        * too many metacharacters, i.e. those which are recognized by
        * both the regular expression engine and the SQL LIKE
        * statement ([...] and [^...]). Those metacharacters have
        * to be manually unescaped here. */
        builder.Replace(@"\[", "[").Replace(@"\]", "]").Replace(@"\^", "^");

        // put SQL LIKE wildcard literals back
        builder.Replace("[.*]", "[%]").Replace("[.]", "[_]");

        return builder.ToString();
    }
}
```

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by lmk1988** [comment]
Hi @JonathanMagnan,

Yea, it's because the older version does not have ^$
`
// and add regex begining of and end of line tokens so '%abc' and 'abc%' work as expected
builder.Append("^").Append(Regex.Escape(pattern)).Append("$");
`
which fixes starts with and ends with LIKE patterns

:smile:  thanks alot

**Comment by JonathanMagnan** [comment]
Hello @lmk1988 ,

A new version has been released with this change.

Let me know if everything now works as expected.

Best Regards,

Jonathan

**Comment by lmk1988** [comment]
Hi @JonathanMagnan,

Yup, it works with `LIKE 'aaa%'` queries now
Thanks alot 😄

**Comment by JonathanMagnan** [comment]
No problem,

Thank at you for having provided the solution ;)
