### ISSUE TITLE
Null-values should not be inserted into unique indexes. NMemory.Exceptions.MultipleUniqueKeyFoundException: 'Unique key violation (Name). Error code: GenericError'

### ISSUE THREAD

**Issue by JohanLindvall** [zzzprojects/nmemory#34]
The following program fails to run using NMemory 3.0.0 (from NuGet). I believe the issue is that the Items with a null index value shouldn't be inserted into the index at all.

The second insert fails with `NMemory.Exceptions.MultipleUniqueKeyFoundException: 'Unique key violation (Name). Error code: GenericError'`

```
using System;
using NMemory;
using NMemory.Indexes;
using NMemory.Tables;

namespace Nmemory_Index
{
    class Program
    {
        static void Main(string[] args)
        {
            var guid = Guid.NewGuid();
            var db = new MyDatabase();
            var item1 = new Item { Key = 1, Id = guid };
            var item2 = new Item { Key = 2, Id = guid };
            db.Items.Insert(item1);
            db.Items.Insert(item2);
        }
    }

    public class Item
    {
        public int Key { get; set; }

        public Guid Id { get; set; }

        public string Name { get; set; }
    }

    public class MyDatabase : Database
    {
        public MyDatabase()
        {
            var itemTable = Tables.Create<Item, int>(p => p.Key, null);

            var itemIndex = itemTable.CreateUniqueIndex(new RedBlackTreeIndexFactory(), item => item.Name);

            // The following two indexes also fail
            // var itemIndex = itemTable.CreateUniqueIndex(new RedBlackTreeIndexFactory(), item => new { item.Name });
            // var itemIndex = itemTable.CreateUniqueIndex(new RedBlackTreeIndexFactory(), item => new { item.Id, item.Name });

            this.Items = itemTable;
        }

        public ITable<Item> Items { get; private set; }
    }
}
```

**Comment by JonathanMagnan** [comment]
Hello @JohanLindvall ,

I believe it works as expected, you can try the same with `SQL Server` and you will get an error

> Cannot insert duplicate key row in object 'dbo.Items' with unique index 'IX_Name'. The duplicate key value is (<NULL>).

```sql
CREATE TABLE [dbo].[Items]
(
	[Key] [INT] IDENTITY(1, 1) NOT NULL,
	[Id] [UNIQUEIDENTIFIER] NULL,
	[Name] [VARCHAR](50) NULL,
	CONSTRAINT [PK_Items]
		PRIMARY KEY CLUSTERED ([Key] ASC) ON [PRIMARY]
) ON [PRIMARY];
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Name]
ON [dbo].[Items] ([Name] ASC) ON [PRIMARY];
GO


INSERT INTO [Items] (Id)
VALUES (NEWID());
INSERT INTO [Items] (Id)
VALUES (NEWID());
```

Let me know if you need a better explanation about what it's the normal behavior.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JohanLindvall** [comment]
You are right. I missed that my SQL server index was actually filtered. Apologies for misusing the bug report for a question - does NMemory support filtered indexes?

**Comment by JonathanMagnan** [comment]
Unfortunately no,

I believe it's currently out of the scope that we can offer for now in this library. Unfortunately, adding such feature will take more time than we can afford ;(
