### ISSUE TITLE
Very useful. Thank you

### ISSUE THREAD

**Issue by sdg002** [zzzprojects/nmemory#35]

**Comment by JonathanMagnan** [comment]
Hello @sdg002 ,

Thank you for letting us know, I'm happy that you like this library ;)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
