### ISSUE TITLE
Composite primary key 

### ISSUE THREAD

**Issue by aristid-lavri** [zzzprojects/nmemory#41]
### Description
How can i create table with composite primary key ?

```c#

public class MemberGroup
        {
            public int Id { get; set; }
            public int GroupId { get; set; }
            public int MemberId { get; set; }
        }

public class Member
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

public class Group
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        

```

**Comment by aristid-lavri** [comment]
I found the solution it worked fine

using tuple 
```c#
 var memberGroup = base.Tables
                    .Create<MemberGroup, Tuple<int,int>>(gc => Tuple.Create(gc.MemberId,gc.GroupId),
                    new IdentitySpecification<MemberGroup>(x => x.Id, 1, 1));
```

**Comment by JonathanMagnan** [comment]
Oh great ;)

Thank for letting me know,

My developer was about to start it and he reported to me that you found it,

Have a great day,

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
