### ISSUE TITLE
Use same class for different ITable interface implementation

### ISSUE THREAD

**Issue by azhe403** [zzzprojects/nmemory#48]
I have two table here, `FloodActivities `and `MataActivities` like below

![image](https://user-images.githubusercontent.com/17938038/159053377-7658a8c4-81da-4f67-bd5d-2ae556220d4f.png)

When I use same class `HitActivity` for both ITable, `MataActivities` table is never store data. it always null.
And after I make difference class for that's, this issue no longer available.

It must use a difference class for both ITable?

**Comment by JonathanMagnan** [comment]
Hello @azhe403 ,
 
Do you think you could provide a **runnable project sample** for this issue? It will help my developer to get started to investigate it faster and make sure nothing is missing.

_Providing a project sample is now **REQUIRED**. It happened **too many times** that something **was missing** to investigate and/or answer an issue._

_Try to create a new project with only the minimal code (having too many non-related codes doesn’t help either)._  

You can send it to info@zzzprojects.com if you need to keep the source private

Best Regards,
 
Jon
 
---
 
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)
