### ISSUE TITLE
Seems like a misleading documentation? ;-)

### ISSUE THREAD

**Issue by voroninp** [zzzprojects/nmemory#49]
![image](https://user-images.githubusercontent.com/9202028/221576591-372a1ebf-446d-4881-9717-0d6a10c2c44a.png)

![image](https://user-images.githubusercontent.com/9202028/221578161-7a287794-9bd1-459d-abfb-93c101fbe662.png)

**Comment by tutorialpedia** [comment]
Hello @voroninp ,

Thank you for reporting. Indeed we need to fix this ;)

The change will be included the next time our website is deployed.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @voroninp ,

Thank you for reporting. Indeed we need to fix this ;)

The change will be included the next time our website is deployed.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Thank again @voroninp ,

The page has been updated
