### ISSUE TITLE
Is it possible to avoid cloning objects and just to reuse references? 

### ISSUE THREAD

**Issue by voroninp** [zzzprojects/nmemory#50]
## 1. Description
NMemory clones instances returned from the database. Well, this is indeed an expected behavior.

However, if we have immutable classes, returning the same instances once being inserted into the table seems to be beneficial. It gives a performance boost as there's no need for cloning and memory allocation.

Is it possible to tweak NMemory to do exactly this?

**Comment by JonathanMagnan** [comment]
Hello @voroninp ,

It could definitely be possible, but I'm not sure if that really works if adding an option for this. 

While you are right, and you will get a performance boost + memory allocation, you will lose the ability to use transactions as change will be made directly on the entity and not a cloned instance that can go to the garbage collector whenever we want.

As you can understand, it cannot be the default behavior but could be done through an option. However, you can correct me if I'm wrong, but this option doesn't seem to be worth it as normally, a memory provider like this one is not done to handle millions of entities.

Best Regards,

Jon

**Comment by voroninp** [comment]
> as change will be made directly on the entity

This is true, but that's why I mentioned immutable entities.

> a memory provider like this one is not done to handle millions of entities.

Well... ;-)
 Our software builds reports, but currently we are not working with any OLAP storage, we just read all data into memory (tens of GBs, actually), and put it into dictionaries, but dictionaries are fine for PKs, and unique or very selective indices. However, they do not provide querying flexibility.

**Comment by JonathanMagnan** [comment]
> This is true, but that's why I mentioned immutable entities.

Good point ;)

Sure, I will try to look at it to check the difficulty of adding that option. When I looked this morning, it seemed to take only 1h to do this request or so.

**Comment by voroninp** [comment]
@JonathanMagnan also, if entities are not cloned, then no need for default constructor, hence positional records get support ;-)

**Comment by JonathanMagnan** [comment]
Hello @voroninp ,

We currently have a branch to test this feature: https://github.com/zzzprojects/nmemory/commit/7bb5c0a64f590c642200f6c7a4dfde2593e80724

It will be possible to activate this behavior with the following options when the branch is merged: `NMemory.NMemoryManager.DisableObjectCloning = true;`

I believe unless my developer finds some major issue, we will be able to release it very soon as it only impacts people that turn on this option (you!)

**Comment by voroninp** [comment]
@JonathanMagnan , thanks, I'll take a look.

This will be totally ok for us, but design-wise should not it be an option adjusted per table?

**Comment by JonathanMagnan** [comment]
Hello @voroninp ,

In the best world, both should exists. So indeed you are right and it should also exists by table.

However, we are currently very limited in time so doing only globally was the easiest way.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @voroninp ,

The v3.1.5 has been released, so you can now directly try it from NuGet if you want.

I will close the issue, but if you find anything, just let us know, and I will re-open it.

Best Regards,

Jon

---

**Are you finding this library useful? If so, please consider supporting its continued development by [becoming a sponsor](https://github.com/sponsors/zzzprojects).**

Additionally, if you think your enterprise would benefit from this library, we encourage you to suggest they [become a sponsor](https://github.com/sponsors/zzzprojects) as well. Your support will help ensure this library remains alive and well-supported.
