### ISSUE TITLE
DefaultTable.InsertCore does not respect DisableObjectCloning

### ISSUE THREAD

**Issue by masonwheeler** [zzzprojects/nmemory#52]
## 1. Description
With `NMemoryManager.DisableObjectCloning` set to `true`, object cloning should not happen.  But when inserting an object into a table, the code still clones the object before checking to see if `DisableObjectCloning` is set.
https://github.com/zzzprojects/nmemory/blob/master/Main/Source/NMemory.Shared/Tables/DefaultTable.cs#L83

## 2. Exception
If the entity type does not have a parameterless constructor defined, this raises an exception:

```
System.MissingMethodException: Cannot dynamically create an instance of type '[entity type]'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at NMemory.Tables.Table`2.CreateStoredEntity()
   at NMemory.Tables.DefaultTable`2.InsertCore(TEntity entity, Transaction transaction)
```

The fix is obvious.  These two lines should be moved to inside the `else` block of the `if` immediately following:
```
            TEntity storedEntity = this.CreateStoredEntity();
            Action<TEntity, TEntity> cloner = this.EntityService.CloneProperties<TEntity>;
```
Given that the local variables they define are only used within the `else` block, this would not break the code, and would fix the problem described here of objects being cloned when NMemory is configured to not clone them.

**Comment by JonathanMagnan** [comment]
Hello @masonwheeler ,

Thank you for reporting. My developer will look at your proposed fix.

Best Regards,

Jon

**Comment by masonwheeler** [comment]
@JonathanMagnan Heard anything back yet?  This is a very simple fix to an obvious problem, that is holding up my project.

**Comment by JonathanMagnan** [comment]
Hello @masonwheeler ,

That's a free project; we normally work on free projects during the weekend for "fun".

I'm pretty sure as well it will be approved and released next week.

Meanwhile, you can fork this repo and add it to your solution to continue to progress.

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @masonwheeler ,

The v3.1.6 is now available.

Could you try it and let us know if everything is working now?

Best Regards,

Jon

**Comment by masonwheeler** [comment]
Yes, the latest NuGet build is working now.  Thanks!
