### ISSUE TITLE
Create table not accept List<string> prop

### ISSUE THREAD

**Issue by ednsinf** [zzzprojects/nmemory#55]
The type of 'xxxx' property is a reference type.
Parameter name: TEntity'

Class
 public class Test
 {        
     public long Id { get; set; }
     public string Term1{ get; set; }
     public string Term2{ get; set; }  
     public List<string> Join{ get; set; }
 }

**Comment by JonathanMagnan** [comment]
Hello @ednsinf ,

Could you provide us with more detail, such as a runnable project? It doesn't necessarily need to be your solution, just a new project that has the issue.

At this moment, it's missing some information to be able to assign this to one of my developers.

Best Regards,

Jon

**Comment by ednsinf** [comment]
This project not allow create table with props of typed List<T>. It´s very limited. 

```
public class Test
{
public long Id { get; set; }
public string Term1 { get; set; }
public string Term2 { get; set; }
public List<string> Terms { get; set; } => error
}
```

**Comment by JonathanMagnan** [comment]
Hello @ednsinf ,

Indeed, your class should correspond to your table in NMemory. There is currently no way to know how to save the `Terms` property as a column in a database.

There is some way to overcome this limitation for example, by putting the `Terms` property internal. NMemory will only take public properties.

Here is an online example: https://dotnetfiddle.net/ifjM35

Best Regards,

Jon

**Comment by ednsinf** [comment]
Internal props not solve my problem. We decide use another solution. Thanks.
