### ISSUE TITLE
Case-insensitive text search

### ISSUE THREAD

**Issue by stevehansen** [zzzprojects/nmemory#6]
Using this in combination with Effort, our default collation is defined as case-insensitive so that searching for "test" would also "Test" and "TEST". Exported our data, everything is running in-memory. But now the searching only matches exact case. Entity Framework doesn't allow passing an comparer in queryable code so it looks I'm stuck here.

Any suggestions?

**Comment by tamasflamich** [comment]
Hi,

Yes, capability for being case insensitive has been requested long ago. Unfortunately this would require deep architectural changes that I probably will not have resources for in the foreseeable future.

**Comment by JonathanMagnan** [comment]
Hello @stevehansen ,

I will close this request next week.

At this moment, I'm not sure how we could handle it in `NMemory` without having an impact on some existing projects.

As @tamasflamich said, supporting `case insensitive` will require some deep changes which I believe will lead to more problem than the one it will solve.

There is some workaround but they all require you to change some code on your side which I do not believe is what you want.

**Comment by stevehansen** [comment]
Seems reasonable

**Comment by JonathanMagnan** [comment]
Hello @stevehansen ,

Just to let you known, there is a pull request on `Effort`: https://github.com/zzzprojects/EntityFramework-Effort/pull/58

I recommend you to subscribe to it. We will for sure look at it soon.

So even if might be too hard in `NMemory` to do such a thing, it doesn't mean that it will not be done in `Effort`.

Best Regards,

Jonathan
