### ISSUE TITLE
Update to 1.1.1 producing HRESULT: 0x80131045

### ISSUE THREAD

**Issue by deathgore** [zzzprojects/nmemory#7]
'Could not load file or assembly 'file:///C:\jenkins\workspace...\packages\NMemory.1.1.1\lib\net45\NMemory.dll' or one of its dependencies.
Strong name signature could not be verified. 
The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

Only solution which worked was to downgrade reference to 1.1.0.

**Comment by geirsagberg** [comment]
I have the same issue. Downgrading worked for me as well.

**Comment by tamasflamich** [comment]
My fault, the keypair was not in place for making a proper signed build. I fixed this with a new release (1.1.2)
