### ISSUE TITLE
Question : Is there a way to load data multiple times (refresh reload...)

### ISSUE THREAD

**Issue by CedricDumont** [zzzprojects/nmemory#9]
Hello,

I know this project is used by Effort. I've created a framework to automate testing based on it, I use transient connection so that I start with new loaded data (for info here : https://github.com/CedricDumont/CExtensions-Net/wiki/CExtensions-Effort-Home) . 

So I create the database on every test 
In Effort, on DbManager, there is a [ClearTables](https://github.com/tamasflamich/effort/blob/develop/Main/Source/Effort/Internal/DbManagement/DbContainerManagerWrapper.cs)
I've hacked the code and added a mothod on [EffortConnection](https://github.com/tamasflamich/effort/blob/develop/Main/Source/Effort/Provider/EffortConnection.cs) class to clear the tables. That's ok. But When I want to load data, there is the method on [ExtendedTable2](https://github.com/tamasflamich/effort/blob/develop/Main/Source/Effort/Internal/DbManagement/Engine/ExtendedTable%602.cs#L76) that  checks for Indexes and PrimaryKeyIndex and when I pass a second time in this method (to reload new data), it fails. 
Right now, what I did is simply commented the lines and it is working, but I would like to do it cleaner by calling some kind of method on NMemory like so:

Database.Clear()
Database.LoadData(bool skipConstraints).

perhaps this feature already exists, but I cannot find documentation on this...

Would it be difficult to implement it ? if not I can do it, but need some info where is the best place to do so...

kind regards

**Comment by JonathanMagnan** [comment]
Hello @CedricDumont ,

I will close this issue since I believe 3 years later, this is probably not required by you anymore.

If you still need someone like it, feel free to report it again here: https://github.com/zzzprojects/EntityFramework-Effort

Best Regards,

Jonathan
